FROM python:3.10-slim AS build-stage
COPY --from=jaybraker/python_scraper_base:latest /app/venv /app/venv

WORKDIR /app/
COPY . .

RUN venv/bin/python -m jupyter nbconvert --to script *.ipynb
RUN if ! [ -d out ]; then mkdir out; fi
CMD ["venv/bin/python", "ventos_scraper_notebook.py"]