FROM jaybraker/python_scraper_base:latest AS build

COPY --from=stage build /app/venv /app/

WORKDIR /app/

RUN venv/bin/python -m jupyter nbconvert --to script *.ipynb
RUN venv/bin/python ventos_scraper_notebook.py