# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Scrape catalog

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest jupyter nbconvert
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Convert Notebook to .py
      run: |
        jupyter nbconvert --to script ventos_scaper_notebook.ipynb
    - name: start scraping
      run: python3 ventos_scraper_notebook.py
    - uses: actions/upload-artifact@v2
      with:
        name: chemicals-catalog
        path: ./chems.csv
