# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Scrape catalog

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Pull base image
      run: docker pull jaybraker/python_scraper_base:latest
    - name: Build temp application image
      run: docker image build -f Dockerfile.scraper . -t ventos_scrape:latest
    - name: Create Output folder
      run: |
        echo ${{ github.workspace }}
        mkdir -p ${{ github.workspace }}/out
    - name: View Output folder
      run: ls ${{ github.workspace }}/out/
    - name: Run Scraper
      run: docker run -a STDOUT --rm -v $(pwd)/out/:/app/out ventos_scrape:latest
    - name: View Output folder
      run: |
        ls $(pwd)/out/
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        working-directory: ${{ github.workspace }}/out/
        name: chem-catalog
        path: chems.csv
